version: '2'

services:
 transmission:
  build: .
  cap_add:
    - NET_ADMIN
  devices:
    - "/dev/net/tun"
  restart: always
  ports:
    - "9091:9091"
    - "8888:8888"
  dns:
    - 8.8.8.8
    - 8.8.4.4
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /Users/system/build/torrent:/data
  environment:
    - WINDSCRIBE_USERNAME=${WINDSCRIBE_USERNAME}
    - WINDSCRIBE_PASSWORD=${WINDSCRIBE_PASSWORD}
    - HOST_PORT=${HOST_PORT:-8888} #Pass for echo purposes
    - WINDSCRIBE_COUNTRY=${WINDSCRIBE_COUNTRY}
    - LOCAL_NETWORK=192.168.0.0/24

#  proxy:
#   image: haugene/transmission-openvpn-proxy:latest-armhf
#   links:
#     - transmission
#   ports:
#     - "8080:8080"
#   volumes:
#     - /etc/localtime:/etc/localtime:ro

#  rss:
#   image: haugene/transmission-rss:latest-armhf
#   links:
#     - transmission
#   environment:
#     - RSS_URL=http://.../xxxxx.rss
